### ISSUE TITLE
Poesie not working with macOS catalina

### ISSUE THREAD

**Issue by amaurydavid** [NijiDigital/poesie#20] opened 2019-11-20 13:14 UTC
Since I upgraded to macOS Catalina and the removal of the default ruby environment, it seems that running poesie no longer works:
`/usr/local/bin/poesie: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory`

Other ruby tools like cocoapods or fastlane work well with the ruby env I set up with `rbenv`, but poesie doesn't. Is there an hard coded path to the default system ruby?

**Comment by afaucogney** [comment] 2020-07-07 13:55
@amaurydavid Hi, I updated to Catalina and do not have any issue. Did you solve your problem ?

**Comment by amaurydavid** [comment] 2020-07-08 06:57
Nope :( I no longer have access to the project using poesie so I won't be able to provide any details sry.

**Comment by nvergoz-niji** [comment] 2020-07-16 08:54
The issue is about ruby gems.

This post helped me https://github.com/fastlane/fastlane/issues/15460#issuecomment-539947237

Try to figured it out if the gem and ruby binaries your are using by doing `which ruby` `which gem` `sudo which ruby` `sudo which gem`. And for a specific gem (like bundler) `gem which bundle` and `which bundle`. 
You should see that some of them don't point to the same binary folder (so not the same ruby version either)

I solved this by uninstalling all gems (delete gems folder content as well)

In my case, I use rbenv. But I switched everything to the system's ruby version (for global, local and shell)
I set the GEM_HOME in my .zshrc or .bashrc file to ~/.gems (so I don't need to use sudo to install my gems)
And then reinstall my gems. The issue with poesie on a XCode project was bundler, so I did a `gem install bundler fastlane cocoapods` and do a `bundle install` from my project.

**Comment by afaucogney** [comment] 2020-10-02 09:11
As it is not linked to poesie, we can close the issue

**Closed as completed by afaucogney** 2020-10-02 09:11 UTC
